#!/usr/bin/env bash

monitor_laptop="eDP-1"
monitor_main="HDMI-A-1"
monitor_secondary="DP-1"

# FIXME Auto-detect this somehow (USB hub?)
WORK_LOCATION=$(tail -1 /tmp/WORK_LOCATION)
WORK_LOCATION=${WORK_LOCATION:-office}

if [[ $WORK_LOCATION == office ]]
then
    swaymsg "output $monitor_laptop      mode 2880x1800 pos 0 2940"
    swaymsg "output $monitor_main        mode 2560x1440 pos 1440 2400"
    swaymsg "output $monitor_secondary   mode 3840x2160 pos 4000 0"
    swaymsg "output $monitor_secondary transform 90"
elif [[ $WORK_LOCATION == home ]]
then

    swaymsg "output $monitor_laptop      mode 2880x1800         pos 0 1440"
    swaymsg "output $monitor_main        mode 3840x2160         pos 2560 0"
    swaymsg "output $monitor_secondary   mode 3840x2160         pos 0 0"
    swaymsg "output $monitor_laptop      scale 1.5"
    swaymsg "output $monitor_main        scale 1.5"
    swaymsg "output $monitor_secondary   scale 1.5"
fi
