#!/usr/bin/env bash

function set_monitors() {
    raw=$(swaymsg -t get\_outputs | jq '.[].name')
    monitor_laptop=$(echo "$raw" | grep -Po 'eDP-\d') # Laptop
    monitor_main=$(echo "$raw" | grep -Po 'HDMI-A-\d') # Though HDMI port on laptop
    monitor_secondary=$(echo "$raw" | grep -Po '\bDP-\d') # Through HDMI port on dock
}
set_monitors

# Auto-detect work location
function detect_location() {
    OFFICE_SIGN='BRIO Ultra HD Webcam'
    HOME_SIGN='G502 SE HERO Gaming Mouse'
    if [[ $(lsusb | grep "$OFFICE_SIGN") ]]
    then
        echo "office"
    elif [[ $(lsusb | grep "$HOME_SIGN") ]]
    then
        echo "home"
    fi
}
WORK_LOCATION=$(detect_location)
WORK_LOCATION=${WORK_LOCATION:-office}

if [[ $WORK_LOCATION == office ]]
then
    swaymsg "output $monitor_laptop      mode 2880x1800 pos 0 2940"
    swaymsg "output $monitor_main        mode 2560x1440 pos 1440 2400"
    swaymsg "output $monitor_secondary   mode 3840x2160 pos 4000 0"
    swaymsg "output $monitor_secondary transform 90"
elif [[ $WORK_LOCATION == home ]]
then
    swaymsg "output $monitor_laptop disable"

    swaymsg "output $monitor_main        mode 3840x2160         pos 2560 0"
    swaymsg "output $monitor_secondary   mode 3840x2160         pos 0 0"
    # Yeah yeah, I need new glasses
    swaymsg "output $monitor_main        scale 1.5"
    swaymsg "output $monitor_secondary   scale 1.5"
fi
