#!/bin/zsh

### convenience
alias    ls='eza --time-style="+%Y-%m-%d" --group-directories-first --hyperlink --colour=never -hlF always --icons --git'
alias    ll='eza -a --time-style="long-iso" --group-directories-first --no-permissions --hyperlink --colour=never -hoalF always --icons --git'
alias     l='eza --time-style=relative --group-directories-first --hyperlink --colour=auto -hlF=always --icons --no-permissions --no-user'
alias    la='\ls --group-directories-first -pa'
alias    l.='\ls --group-directories-first -halpd .* --time-style="+%Y-%m-%dT%H:%M:%S"'
alias     j='jobs -l'
alias     h='history'
alias     t='\tree -Fn --dirsfirst -I __pycache__\|node_modules --charset=ASCII --noreport'
alias zshrf="source ${HOME}/.zshrc"
alias  tmux="tmux -u"
alias    py="python -Bu"
alias    dc="docker compose"
alias   vim='nvim'
alias    vi='nvim'
alias     v='nvim'
alias    vt='nvim -c":NERDTree"'
alias    tm='tmux'
alias     r="EDITOR=nvim VISUAL=nvim ranger"
alias     k='kubectl'
alias     d='docker'
alias     g='git'
alias    tf='terraform'

### convenience (more specific)
alias   mem='ps ax -o %mem=--MEM--,user=---USER---,pid=---PID--,cmd | grep -v root | sort -Vr'
alias   cpu="watch 'ps ax -o %cpu=--CPU--,user=---USER---,pid=---PID--,cmd | grep -v root | sort -Vr | head -10'"
alias ginit='tmux new-session -s$( echo $PWD | rev | cut -d/ -f1 | rev ) \; rename-window -t0 git \; new-window -nsrc \; new-window -nrun \; next-window \; send-keys "clear;git status -bs" Enter'
alias npm-ls="cat package.json|jq -r '.scripts |to_entries|map(\"\(.key)___\(.value)\")|.[]' | column -nts'___'"
alias  vbuff='vim "+normal G" <(tmux capture-pane \; show-buffer | cat -s -)'  # Pipe tmux buffer to vim, squeezing lines, and placing cursor at EOL
alias   time='/usr/bin/time -f%E'

# TODO slice -N : show top and bottom of output plus N lines context below and above

### convenience pipes (global)
alias -g      G='| grep --color'
alias -g   grev='| grep --color -v'
alias -g      L='| less -R'
alias -g      H='| head'
alias -g      T='| tail'
alias -g      J="| jq '.'"  # Would be nicer if this was default without arg
alias -g  quiet='2> /dev/null'
alias -g silent='&> /dev/null'
alias -g      C='| column -ts,'

### info aliases
alias ports='sudo netstat -uplant'        # list all TCP/UDP ports on the server
alias    df='df -H'                       # report file system disk space usage
alias    du='du -ch --summarize'          # print estimated disk usage
alias uptime='uptime --pretty'            # show uptime output in 'pretty' time format

### safety aliases
alias    mv='mv -vi'                      # verbose + prompts for safety
alias    rm='rm -vI'                      # "
alias    cp='cp -vi'                      # "
alias    ln='ln -vi'                      # "
alias crontab='crontab -i'                # Prompt before deleting user's crontab o_o;;

# Used to synch/repro configurations between systems
# NOTE You're gonna want this: `echo '*' > ~/.gitignore`
alias skel='git --work-tree=$HOME --git-dir=$HOME/skel/.git'

# Fun
alias hackerman='~/trees/hackerman/bin/hackerman'
alias notes='~/trees/notes-cli/bin/notes'
alias hack='~/trees/hackerman/bin/hackerman -s10 -q fbi'
alias vacay="gcal -H '\e[0;5;1m:\e[0m:\e[32;1m:\e[0m' -q CA_ON -y $(date +'%Y')"
alias asdf="echo 'Hang in there, bud :)'"
alias meow="MEOW=MEOW LINES=$(tput lines) NUM=$(tput cols) node -e 'const{LINES,NUM,MEOW}=process.env;for(let i=0;i<LINES;i++)console.log(MEOW.repeat(NUM / MEOW.length))'"

alias write_daily_page="vim -S ~w/page.vim --cmd 'let writing_mode=1' ~w/daily-pages/$(date -I).page.md"

# General tilde expansions
hash -d t=$HOME/trees
hash -d s=$HOME/sandbox
hash -d c=$HOME/.config
hash -d D=$HOME/Downloads
hash -d w=$HOME/sandbox/writing
hash -d usb=/media/jm
