#!/bin/zsh

### convenience
alias    ls='\ls -l -phF'
alias    ll='\ls -halp -F'
alias     l='\ls -p'
alias    la='\ls -pa'
alias    l.='\ls -halpd .*'
alias    li='file *' # not a good alias, does not take args
alias     j='jobs -l'
alias     h='history'
alias     t='\tree -Fn --dirsfirst -I node_modules'
alias    td='\tree -Fn --dirsfirst -I node_modules -d' # same, but dirs only
alias  scns='scn -ls'
alias zshrf="source ${HOME}/.zshrc"
alias    nv="nvim" # let's try out this whole neovim thing ...
alias    vi="nvim"
alias   vim="nvim"
alias     p="pandoc -t plain $1"
#alias  tmux="tmux2.3 -2"
alias  tmux="tmux -u"
alias    py="python -Bu"

### convenience (more specific)
alias   mem='ps ax -o %mem=--MEM--,user=---USER---,pid=---PID--,cmd | grep -v root | sort -Vr'

### convenience pipes (global)
alias -g      G='| grep --color'
alias -g   grev='| grep --color -v'
alias -g      L='| less -R'
alias -g      H='| head'
alias -g  quiet='2> /dev/null'
alias -g silent='&> /dev/null'

### info aliases
alias ports='sudo netstat -uplant'        # list all TCP/UDP ports on the server
alias    df='df -H'                       # report file system disk space usage
alias    du='du -ch --summarize'          # print estimated disk usage
alias uptime='uptime --pretty'            # show uptime output in 'pretty' time format

### safety aliases
alias    mv='mv -i'                       # prompts for safety
alias    rm='rm -I'                       # "
alias    cp='cp -i'                       # "
alias    ln='ln -i'                       # "

### scripts 
alias  f='~/scripts/superfind.sh'   # Usage: f  <dir> <filename>
alias fr='~/scripts/repofind.sh'    # Usage: f  <dir> <reponame>
alias  r='~/scripts/superrm.sh'     # Usage: rm <dir> (with tree output + prompt)
alias  s='~/scripts/supergrep.sh'   # Usage: s  <dir> <pattern>
alias  d='~/scripts/difffiles.sh'   # Usage: d  <dir1> <dir2>
alias  c='~/scripts/ipinfo.sh'      # Usage: c  <ip>
alias  e='~/scripts/penv.sh'        # Usage: e
alias gm='~/scripts/gd-sum.sh'      # Usage: gm
alias al='~/scripts/aliases.sh'     # Usage: al
alias todo='~/scripts/todo.sh'      # Usage: todo

alias crawl='~/scripts/crawl.sh'    # Usage: crawl [OPTIONS]... [FILE]
alias zshdf='diff -r ~/.zshrc.dir ~/env/zsh/.zshrc.dir' # TEMP - recursive diff of active and vc zsh env files

### git aliases
alias   g='git'                     #
alias  st='git status -s -b'        #shortform git status + branch info
alias  gs='git status'              #
alias  gd='git diff'                #
alias gdd="git diff --color-words='[^[:space:]]|([[:alnum:]]|UTF_8_GUARD)+'" #show character substitutions on the same line (and avert wordsalad)
alias gds='git diff --shortstat'    # just the stats, ma'am
alias gdc='git diff --cached'       # what did I just add ...?
alias gsl='git stash list --date=local' #
alias  gt='git log --graph --oneline --decorate --all' #
alias  "g?"='git remote -v update'    #fetch updates from all branches no set to skipDefaultUpdate (show ahead or behind)
alias  gf='git log -p --follow --oneline --' #
alias gfp='git log -p --follow --'  #
function gg() { git grep "$*"; }  # simpler git-grep (concatenates params)

alias gp='git pull \
    --recurse-submodules'         # update submodules
alias "git clone"='git clone \
    --resursive'                  # update submodule(s) when cloning
alias gpu='git push'              #
alias  ga='git add'               #
alias  gc='git checkout'          # shortcuts
alias gcm='git commit'            #
#alias  gl='git log --name-status' # show file action summaries
alias  gl='git log --stat'        # show file insertions, deletions
alias glp='git log \
    --patch-with-stat'            # show sum insert/deletes
alias  gb='git branch'
alias gbr='git show-branch'       # show common commits between branches
alias gcf='git commit -F- <<EOF'  # use heredocs for commit message
alias gap='git add --patch'       # commit individual hunks
alias gtr='git ls-tree -r HEAD --name-only --full-name | xargs file | egrep ".*:\s" --color' # list all tracked files in current branch + file information (files highlighted)
alias  gw='watch -d --color git diff --color' # watch for changes, pass colours

# Used to synch/repro configurations between systems
alias skel='git --work-tree=$HOME --git-dir=$HOME/.skel'

