#!/bin/zsh

### convenience
alias    ls='\ls -l -phFrt --time-style="+%Y-%m-%dT%H:%M:%S"'
alias    ll='\ls -halp -F --time-style="+%Y-%m-%dT%H:%M:%S"'
alias     l='\ls -p --time-style="+%Y-%m-%dT%H:%M:%S"'
alias    la='\ls -pa --time-style="+%Y-%m-%dT%H:%M:%S"'
alias    l.='\ls -halpd .* --time-style="+%Y-%m-%dT%H:%M:%S"'
alias     j='jobs -l'
alias     h='history'
alias     t='\tree -Fn --dirsfirst -I __pycache__\|node_modules --charset=ASCII --noreport'
alias zshrf="source ${HOME}/.zshrc"
alias  tmux="tmux -u"
alias    py="python -Bu"
alias    dc="docker-compose"
alias   vim='nvim'
alias    vi='nvim'
alias     v='nvim'
alias    vt='nvim -c":NERDTree"'
alias    tm='tmux'
alias     r="EDITOR=nvim VISUAL=nvim ranger"
alias     k='kubectl'

### convenience (more specific)
alias   mem='ps ax -o %mem=--MEM--,user=---USER---,pid=---PID--,cmd | grep -v root | sort -Vr'
alias   cpu="watch 'ps ax -o %cpu=--CPU--,user=---USER---,pid=---PID--,cmd | grep -v root | sort -Vr | head -10'"
alias ginit='tmux new-session -s$( echo $PWD | rev | cut -d/ -f1 | rev ) \; rename-window -t0 git \; new-window -nsrc \; new-window -nrun \; next-window \; send-keys "clear;git status -bs" Enter'
alias npm-ls="cat package.json|jq -r '.scripts |to_entries|map(\"\(.key)___\(.value)\")|.[]' | column -nts'___'"
alias  vbuff='vim "+normal G" <(tmux capture-pane \; show-buffer | cat -s -)'  # Pipe tmux buffer to vim, squeezing lines, and placing cursor at EOL

# TODO slice -N : show top and bottom of output plus N lines context below and above

### convenience pipes (global)
alias -g      G='| grep --color'
alias -g   grev='| grep --color -v'
alias -g      L='| less -R'
alias -g      H='| head'
alias -g      T='| tail'
alias -g      J="| jq '.'"  # Would be nicer if this was default without arg
alias -g  quiet='2> /dev/null'
alias -g silent='&> /dev/null'
alias -g      C='| column -nts,'

### info aliases
alias ports='sudo netstat -uplant'        # list all TCP/UDP ports on the server
alias    df='df -H'                       # report file system disk space usage
alias    du='du -ch --summarize'          # print estimated disk usage
alias uptime='uptime --pretty'            # show uptime output in 'pretty' time format

### safety aliases
alias    mv='mv -vi'                      # verbose + prompts for safety
alias    rm='rm -vI'                      # "
alias    cp='cp -vi'                      # "
alias    ln='ln -vi'                      # "
alias crontab='crontab -i'                # Prompt before deleting user's crontab o_o;;

### scripts 
alias  f='~/scripts/superfind.sh'   # Usage: f  <dir> <filename>
alias  d='~/scripts/difffiles.sh'   # Usage: d  <dir1> <dir2>
alias  c='~/scripts/ipinfo.sh'      # Usage: c  <ip>
alias  e='~/scripts/penv.sh'        # Usage: e
alias gm='~/scripts/gd-sum.sh'      # Usage: gm
alias todo='~/scripts/todo.sh'      # Usage: todo

alias crawl='~/scripts/crawl.sh'    # Usage: crawl [OPTIONS]... [FILE]

### git aliases
alias vgl='vim -c":Git log"'
alias   g='git'                     #
alias  st='git status -s -b'        #shortform git status + branch info
alias  gs='git status'              #
alias  gd='git diff'                #
alias gdd="git diff --color-words='[^[:space:]]|([[:alnum:]]|UTF_8_GUARD)+'" #show character substitutions on the same line (and avert wordsalad)
alias gds='git diff --shortstat'    # just the stats, ma'am
alias gdc='git diff --cached'       # what did I just add ...?
alias gsl='git stash list --date=local' #
alias  gt='git log --graph --oneline --decorate --all' #
alias  "g?"='git remote -v update'    #fetch updates from all branches no set to skipDefaultUpdate (show ahead or behind)
alias  gf='git log -p --follow --oneline --' #
alias gfp='git log -p --follow --'  #
function gg() { git grep "$*"; }  # simpler git-grep (concatenates params)

alias gp='git pull \
    --recurse-submodules'         # update submodules
alias gpu='git push'              #
alias  ga='git add'               #
alias  gc='git checkout'          # shortcuts
alias gcm='git commit'            #
#alias  gl='git log --name-status' # show file action summaries
alias  gl='git log --stat'        # show file insertions, deletions
alias glp='git log \
    --patch-with-stat'            # show sum insert/deletes
alias  gb='git branch'
alias gbr='git show-branch'       # show common commits between branches
alias gcf='git commit -F- <<EOF'  # use heredocs for commit message
alias gap='git add --patch'       # commit individual hunks
alias gtr='git ls-tree -r HEAD --name-only --full-name | xargs file | egrep ".*:\s" --color' # list all tracked files in current branch + file information (files highlighted)
alias  gw='watch -d --color git diff --color' # watch for changes, pass colours

# Used to synch/repro configurations between systems
# NOTE You're gonna want this: `echo '*' > ~/.gitignore`
alias skel='git --work-tree=$HOME --git-dir=$HOME/.skel/.git'

# Ratehub
alias p='rh-psql-conn'

# Fun
alias hackerman='~/trees/hackerman/bin/hackerman'
alias notes='~/trees/notes-cli/bin/notes'
alias hack='~/trees/hackerman/bin/hackerman -s10 -q fbi'
alias vacay="gcal -H '\e[0;5;1m:\e[0m:\e[32;1m:\e[0m' -q CA_ON -y $(date +'%Y')"
alias asdf="echo 'Hang in there, bud :)'"

