#!/bin/bash

# Redirect output to stderr.
exec 1>&2

# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty

function prompt {
    while true; do
        read -p "$1 [y]es or [n]o " yn
        case $yn in
            [Yy]* ) return 0;;
            [Nn]* ) return 1;;
            * ) echo "Please answer yes or no.";;
        esac
    done
}

wip_code=$(git diff --staged --patch -U0 \
    | awk '/^\+[^\+]/ { print }' \
    | grep -PC2 '(TODO|XXX|WIP|FIXME)')

if [[ $? -ne 1 ]]
then
    echo -e "Found what looks like WIP code or comments:\n$wip_code"
    prompt "Commit anyway?" || exit 1
fi


git diff --staged --patch -U0 \
    | awk '/^\+[^\+]/ { print }' \
    | grep -qw 'debugger' \
    && {
        echo "Can't commit - debug code detected" ; exit 1
    }

exit 0
